import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import { Suspense } from 'react'
import Head from 'next/head'
//import Header from '../src/components/Header'
//import GoodPractices from '../src/components/index/GoodPractices'
//import Footer from '../src/components/Footer'

const Header = dynamic(() => import('../src/components/Header'), { suspense: true })
const GoodPractices = dynamic(() => import('../src/components/index/GoodPractices'), { suspense: true })
const Footer = dynamic(() => import('../src/components/Footer'), { suspense: true })
const Home: NextPage = () => {
  return <>
    <Head>
      <title>Black 4 Green</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Suspense fallback={`Loading...`}>
      <Header />
      <GoodPractices />
      <Footer />
    </Suspense>

  </>
}

export default Home
