import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/index/Header'

const Home: NextPage = () => {
  return <>
    <Head>
      <title>Black 4 Green</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <h1 className="text-3xl font-bold underline text-center">
      Hello world!
    </h1>
  </>
}

export default Home
